### ISSUE TITLE
Regarding EMA Update of Prototypes

### ISSUE THREAD

**Issue by michaelku1** [cvlab-yonsei/DASS#3]
Hi, interesting work. I couldn't seem to find the ema update of prototypes in the code as indicated in the paper. Am I missing something? Thanks.

**Comment by LeeGeon31** [comment]
Please refer to the paper and " trainer" codes.

**Comment by michaelku1** [comment]
Sure, I did look into the trainer code, but there was no code for ema update for the prototypes. Thanks.

![Screenshot from 2023-02-17 15-33-01](https://user-images.githubusercontent.com/48415065/219583448-d41ffe62-c705-47e6-99fe-95137a65ba9d.png)
